#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

if [[ -f .env ]]; then
  set -a
  source .env
  set +a
fi

export OMNICLAW_X402_FACILITATOR_PRIVATE_KEY="${OMNICLAW_X402_FACILITATOR_PRIVATE_KEY:-${SELLER_OMNICLAW_PRIVATE_KEY:-${OMNICLAW_PRIVATE_KEY:-}}}"
export OMNICLAW_X402_FACILITATOR_NETWORK_PROFILE="${OMNICLAW_X402_FACILITATOR_NETWORK_PROFILE:-ARC-TESTNET}"
export OMNICLAW_X402_FACILITATOR_RPC_URL="${OMNICLAW_X402_FACILITATOR_RPC_URL:-https://rpc.testnet.arc.network}"
export OMNICLAW_X402_FACILITATOR_NETWORKS="${OMNICLAW_X402_FACILITATOR_NETWORKS:-eip155:5042002}"
export OMNICLAW_X402_FACILITATOR_PORT="${OMNICLAW_X402_FACILITATOR_PORT:-4022}"
export OMNICLAW_X402_FACILITATOR_HOST="${OMNICLAW_X402_FACILITATOR_HOST:-0.0.0.0}"

if [[ -z "$OMNICLAW_X402_FACILITATOR_PRIVATE_KEY" ]]; then
  echo "Missing facilitator key. Set OMNICLAW_X402_FACILITATOR_PRIVATE_KEY, SELLER_OMNICLAW_PRIVATE_KEY, or OMNICLAW_PRIVATE_KEY."
  exit 1
fi

cat <<EOF

Starting OmniClaw self-hosted x402 exact facilitator.

Network profile: $OMNICLAW_X402_FACILITATOR_NETWORK_PROFILE
Network CAIP-2:  $OMNICLAW_X402_FACILITATOR_NETWORKS
RPC:            $OMNICLAW_X402_FACILITATOR_RPC_URL
URL:            http://127.0.0.1:$OMNICLAW_X402_FACILITATOR_PORT

Health:
  curl http://127.0.0.1:$OMNICLAW_X402_FACILITATOR_PORT/supported

EOF

exec uv run omniclaw facilitator exact \
  --host "$OMNICLAW_X402_FACILITATOR_HOST" \
  --port "$OMNICLAW_X402_FACILITATOR_PORT" \
  --network-profile "$OMNICLAW_X402_FACILITATOR_NETWORK_PROFILE" \
  --network "$OMNICLAW_X402_FACILITATOR_NETWORKS" \
  --rpc-url "$OMNICLAW_X402_FACILITATOR_RPC_URL"
